# Sample configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
#   sidekiq -e production -C /var/www/vhosts/movielala.com/workers_app/current/config/sidekiq.yml
---
:verbose: false
:pidfile: ./tmp/pids/sidekiq.pid
:concurrency:  25
:timeout: 10

production:
  :concurrency: 40

:limits:
  low_priority: 10
  user_create_or_update: 5


process_limits:
  test: 1

:queues:
  - [high_priority, 1]
  - [user_create_or_update, 20]
  - [low_priority, 30]
  - [default, 100]


:ignore_queues:
  - [no_ignore, 10]

:retry:
  - [test, 2]